language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "7"
  - "7.9.0"
  - "6"
  - "5"
  - "4"
  - "3"
  - "0.12"
  - "0.10"

matrix:
  allow_failures:
    - node_js: '3'
    - node_js: '5'
    - node_js: '7'

sudo: false
